use std::sync::Arc;

use axum::routing::{get, post, put};
use axum::Router;
use sqlx::PgPool;

use super::handlers;

pub(crate) fn build_auth_write_routes(write_pool: Arc<PgPool>) -> Router {
    Router::new()
        .route("/plugins", post(handlers::create_plugin_handler))
        .route("/plugins/import", post(handlers::import_plugin_handler))
        .route(
            "/plugins/{plugin_id}",
            put(handlers::update_plugin_handler).delete(handlers::delete_plugin_handler),
        )
        .route(
            "/plugins/{plugin_id}/skills",
            put(handlers::update_plugin_skills_handler),
        )
        .route(
            "/plugins/{plugin_id}/env",
            put(handlers::update_plugin_env_handler),
        )
        .route("/skills", post(handlers::create_skill_handler))
        .route(
            "/skills/sync-files",
            post(handlers::sync_skill_files_handler),
        )
        .route(
            "/skills/{skill_id}",
            put(handlers::update_skill_handler).delete(handlers::delete_skill_handler),
        )
        .route(
            "/skills/{skill_id}/files/{*file_path}",
            put(handlers::update_skill_file_handler),
        )
        .route("/agents", post(handlers::create_agent_handler))
        .route(
            "/agents/{agent_id}",
            put(handlers::update_agent_handler).delete(handlers::delete_agent_handler),
        )
        .route("/mcp-servers", post(handlers::create_mcp_server_handler))
        .route(
            "/mcp-servers/{server_id}",
            put(handlers::update_mcp_server_handler).delete(handlers::delete_mcp_server_handler),
        )
        .route(
            "/mcp-servers/{server_id}/yaml",
            get(handlers::get_mcp_server_yaml_handler)
                .put(handlers::update_mcp_server_yaml_handler),
        )
        .route("/hooks", post(handlers::create_hook_handler))
        .route(
            "/hooks/{hook_id}",
            put(handlers::update_hook_handler).delete(handlers::delete_hook_handler),
        )
        .route(
            "/hooks/{hook_id}/toggle",
            put(handlers::toggle_hook_handler),
        )
        .route("/user-agents", post(handlers::create_user_agent_handler))
        .route(
            "/user-agents/{agent_id}",
            axum::routing::delete(handlers::delete_user_agent_handler),
        )
        .route(
            "/marketplace-plugins/{plugin_id}/ratings",
            post(handlers::submit_rating_handler),
        )
        .route(
            "/user/plugins",
            get(handlers::user_entities::list_user_plugins_handler)
                .post(handlers::user_entities::create_user_plugin_handler),
        )
        .route(
            "/user/plugins/{plugin_id}",
            put(handlers::user_entities::update_user_plugin_handler)
                .delete(handlers::user_entities::delete_user_plugin_handler),
        )
        .route(
            "/user/plugins/{plugin_id}/skills",
            put(handlers::user_entities::set_plugin_skills_handler),
        )
        .route(
            "/user/plugins/{plugin_id}/agents",
            put(handlers::user_entities::set_plugin_agents_handler),
        )
        .route(
            "/user/plugins/{plugin_id}/mcp-servers",
            put(handlers::user_entities::set_plugin_mcp_servers_handler),
        )
        .route(
            "/user/plugins/{plugin_id}/hooks",
            put(handlers::user_entities::set_plugin_hooks_handler),
        )
        .route(
            "/user/skills",
            get(handlers::user_entities::list_user_skills_handler)
                .post(handlers::user_entities::create_user_skill_handler),
        )
        .route(
            "/user/skills/{skill_id}",
            put(handlers::user_entities::update_user_skill_handler)
                .delete(handlers::user_entities::delete_user_skill_handler),
        )
        .route(
            "/user/agents",
            get(handlers::user_entities::list_user_agents_handler)
                .post(handlers::user_entities::create_user_agent_entity_handler),
        )
        .route(
            "/user/agents/{agent_id}",
            put(handlers::user_entities::update_user_agent_entity_handler)
                .delete(handlers::user_entities::delete_user_agent_entity_handler),
        )
        .route(
            "/user/mcp-servers",
            get(handlers::user_entities::list_user_mcp_servers_handler)
                .post(handlers::user_entities::create_user_mcp_server_handler),
        )
        .route(
            "/user/mcp-servers/{server_id}",
            put(handlers::user_entities::update_user_mcp_server_handler)
                .delete(handlers::user_entities::delete_user_mcp_server_handler),
        )
        .route(
            "/user/hooks",
            get(handlers::user_entities::list_user_hooks_handler)
                .post(handlers::user_entities::create_user_hook_handler),
        )
        .route(
            "/user/hooks/{hook_id}",
            put(handlers::user_entities::update_user_hook_handler)
                .delete(handlers::user_entities::delete_user_hook_handler),
        )
        .route(
            "/user/fork/plugin",
            post(handlers::user_entities::fork_org_plugin_handler),
        )
        .route(
            "/user/fork/skill",
            post(handlers::user_entities::fork_org_skill_handler),
        )
        .route(
            "/user/fork/agent",
            post(handlers::user_entities::fork_org_agent_handler),
        )
        .route(
            "/user/fork/mcp-server",
            post(handlers::user_entities::fork_org_mcp_server_handler),
        )
        .route(
            "/user/fork/hook",
            post(handlers::user_entities::fork_org_hook_handler),
        )
        .route(
            "/user/forkable/plugins",
            get(handlers::user_entities::list_forkable_plugins_handler),
        )
        .route(
            "/user/forkable/skills",
            get(handlers::user_entities::list_forkable_skills_handler),
        )
        .route(
            "/user/forkable/agents",
            get(handlers::user_entities::list_forkable_agents_handler),
        )
        .route(
            "/user/forkable/mcp-servers",
            get(handlers::user_entities::list_forkable_mcp_servers_handler),
        )
        .route(
            "/user/forkable/hooks",
            get(handlers::user_entities::list_forkable_hooks_handler),
        )
        .with_state(write_pool)
}
