use super::meta::{CategoryMeta, StepMeta};

pub(super) const CAPABILITY_CATEGORIES: &[CategoryMeta] = &[
    CategoryMeta {
        id: "governance",
        title: "Governance",
        tagline: "Policy that runs on every tool call, not a slide in a security review.",
        story: "Staff engineers want to know what actually happens when an agent goes off-script. This walkthrough fires real PreToolUse hooks against the governance endpoint: a clean admin call passes all three rules, a user-scope agent gets denied at the scope and blocklist layers, and plaintext AWS keys, GitHub PATs, and PEM private keys are blocked before they reach a tool. Every decision lands in an audit table you can query, capped by rate limits you can inspect and hooks you can extend.",
        cost: "",
        feature_url: "https://systemprompt.io/features/governance-pipeline",
        steps: &[
            StepMeta {
                script: "01-happy-path.sh",
                label: "Walk the full hook → allow → execute path",
                narrative: "POSTs a PreToolUse hook for developer_agent calling mcp__systemprompt__systemprompt — the CLI-wrapper tool exposed by the systemprompt MCP server — sees governance return allow, then actually invokes the tool via the CLI with {command: \"admin agents list\"} so you watch the same request land in the real agent runtime. This is the Claude Code hook workflow end to end.",
                outcome: "An allow response from /hooks/govern, a live agents listing returned by the systemprompt MCP server, and a matching row in governance_decisions tied to session demo-happy-path.",
            },
            StepMeta {
                script: "02-refused-path.sh",
                label: "Deny a user-scope agent reaching for an admin MCP tool",
                narrative: "Fires the same hook as associate_agent — a user-scope identity — against the admin-only mcp__systemprompt__list_agents tool. The scope_restriction rule fires at the governance layer, which is the backup line of defense behind tool mapping.",
                outcome: "A deny response citing scope_restriction, plus the matching deny row in governance_decisions — proof that even if tool mapping is bypassed, governance still holds.",
            },
            StepMeta {
                script: "03-audit-trail.sh",
                label: "Query the decisions table and break down cost by agent",
                narrative: "Runs infra db query against governance_decisions to pull the last five decisions with agent, scope, policy, and reason, then calls analytics costs breakdown --by agent. This is the evidence you hand to a compliance reviewer.",
                outcome: "A table showing the allow and deny records from the previous steps with policy names and reasons, plus per-agent cost totals.",
            },
            StepMeta {
                script: "04-governance-happy.sh",
                label: "Allow a clean admin call and show every rule that fired",
                narrative: "POSTs a PreToolUse hook for developer_agent calling Read with a plain file path, then dumps the evaluated_rules column. You see scope_check, secret_injection, and rate_limit each return PASS — not a black-box allow.",
                outcome: "The API returns permissionDecision: allow and the audit row lists all three rules with PASS reasons.",
            },
            StepMeta {
                script: "05-governance-denied.sh",
                label: "Deny a user-scope agent and a destructive tool in one run",
                narrative: "Fires two hook calls as associate_agent: one reaches for an admin-only MCP tool, the other calls delete_agent. scope_check blocks the first; scope_check and blocklist both trigger on the second.",
                outcome: "Two deny responses with distinct policy IDs, logged to governance_decisions so you can see the reason Claude Code would surface to the agent.",
            },
            StepMeta {
                script: "06-secret-breach.sh",
                label: "Block an AWS key, a GitHub PAT, and a private key in tool input",
                narrative: "Sends four PreToolUse hooks as admin-scope developer_agent: a Bash curl carrying AKIA..., a Write dropping ghp_... into .env, a Write piping a PEM key into id_rsa, and a clean Read as control. Secret detection overrides scope.",
                outcome: "Three denies (secret_injection) and one allow, all attributed to an admin agent in the audit table — proof the safety net holds against prompt-injection exfiltration.",
            },
            StepMeta {
                script: "07-rate-limiting.sh",
                label: "Inspect the rate limit, security, and server config",
                narrative: "Calls admin config rate-limits show and compare, then admin config security show and admin config server show. These are the ceilings that cap a runaway agent before governance rules even fire.",
                outcome: "Concrete numbers for per-tier request limits, security posture, and server knobs — the config you would tune in production.",
            },
            StepMeta {
                script: "08-hooks.sh",
                label: "List every registered hook and validate the wiring",
                narrative: "Runs core hooks list to show every PreToolUse, PostToolUse, and lifecycle hook across installed plugins, then core hooks validate to confirm each one resolves. This is the extension surface for your own policies.",
                outcome: "A validated hook inventory with plugin, event, and handler — the exact place you'd drop a custom rule.",
            },
        ],
    },
    CategoryMeta {
        id: "agents",
        title: "Agents",
        tagline: "From \"which agents ship with the platform?\" to a fully traced AI call in five commands.",
        story: "Staff engineers evaluating an agent runtime want three things: to see what's configured, to watch one actually do work, and to trust that every call is auditable. This walkthrough starts at agent discovery, drills into the config and tool scopes that separate an admin agent from a user-scoped one, sends a live message that triggers real MCP tool use, and ends at the execution trace and A2A registry. By the last step you have seen events, artifacts, cost attribution, and service discovery for a single prompt.",
        cost: "API key required",
        feature_url: "https://systemprompt.io/features/closed-loop-agents",
        steps: &[
            StepMeta {
                script: "01-list-agents.sh",
                label: "Discover the agents the platform ships with",
                narrative: "Lists every configured agent via admin agents list, shows process status, then prints the full config for developer_agent (admin scope) and associate_agent (user scope) side by side so you can see exactly how a scoped-down role differs from a privileged one.",
                outcome: "Two-row agent roster, a running-agent status table, and two concrete YAML configs with oauth scopes, port, endpoint, and skill assignments.",
            },
            StepMeta {
                script: "02-agent-config.sh",
                label: "Validate configs and inspect tool scopes",
                narrative: "Shows live process status, then validates both developer_agent and associate_agent and enumerates the MCP tools each one can actually call. The difference is the point: the user-scoped associate cannot reach admin-only MCP tools because the governance scope_check rule denies them at the hook.",
                outcome: "A process status table plus validated configs and two tool inventories that diverge exactly at the admin-only MCP surface.",
            },
            StepMeta {
                script: "03-agent-messaging.sh",
                label: "Send a real message and let the agent work",
                narrative: "Creates a context, messages developer_agent with \"List all agents running on this platform\" in blocking mode, then retrieves the structured artifact it produced. This is the only step that spends money and the only one that exercises the full runtime — A2A message → agent server → AI call → MCP tool use → artifact.",
                outcome: "A reply, an artifact attached to the context, a structured response with tool use events, and a dashboard link scoped to the exact session_id so you can replay the whole thing visually.",
            },
            StepMeta {
                script: "04-agent-tracing.sh",
                label: "Replay what just happened",
                narrative: "Pulls the most recent execution traces, expands the latest one to show every event, lists artifacts produced during the run, and breaks cost down by agent. Nothing is mocked — this reads the same tables the dashboard reads.",
                outcome: "The trace shows AI requests, MCP tool calls with arguments, latency per step, and a dollar figure attributed to developer_agent.",
            },
            StepMeta {
                script: "05-agent-registry.sh",
                label: "See the agents as discoverable services",
                narrative: "Queries the A2A gateway registry so you can see how other agents and external callers discover these workers, then tails the process logs for each agent. A2A is what makes this a platform rather than a single chatbot.",
                outcome: "The registry shows both developer_agent and associate_agent registered with the A2A gateway, and the per-agent logs pull live stdout from the running processes.",
            },
        ],
    },
    CategoryMeta {
        id: "mcp",
        title: "MCP Servers",
        tagline: "Every MCP tool call is inventoried, governed, and costed — watch it catch a leaking secret.",
        story: "MCP is where agents meet real systems, which is exactly where enterprise reviews stall: who is connected, who called what, and what stops a misbehaving model from exfiltrating a secret. This walkthrough starts at the server inventory, then fires a governance hook with a clean payload and a payload containing an AWS key to show allow and deny decisions hitting the audit tables, and ends in the execution analytics view where every tool call is already counted.",
        cost: "",
        feature_url: "https://systemprompt.io/features/mcp-governance",
        steps: &[
            StepMeta {
                script: "01-mcp-servers.sh",
                label: "Inventory the connected MCP servers",
                narrative: "Prints runtime status for every MCP server the platform is connected to, then lists the tools exposed by each one — anchored on the systemprompt server — so you can see what an agent actually has on its tool bar.",
                outcome: "You see which MCP servers are live, their transport and health, and the exact tool names and schemas available to any agent wired into them.",
            },
            StepMeta {
                script: "02-mcp-access-tracking.sh",
                label: "Fire the governance hook, clean then dirty",
                narrative: "POSTs to /hooks/govern twice — once with a benign Read on /src/main.rs and once with a Bash command containing an AWS access key — then calls a tool through the authenticated MCP path and queries the governance_decisions and user_activity tables directly.",
                outcome: "The first call returns permissionDecision allow, the second returns deny with the secret_injection rule as the reason, and the audit tables show both decisions plus the MCP access event rows the dashboard renders.",
            },
            StepMeta {
                script: "03-mcp-tool-execution.sh",
                label: "Zoom out to the execution analytics",
                narrative: "Lists the tools exposed by the systemprompt MCP server, pulls the last ten MCP tool execution log entries, and prints usage stats and seven-day trends. This closes the loop from \"a call happened\" to \"here is how the fleet is being used.\"",
                outcome: "A per-server tool inventory, a chronological tool execution log with latencies, and aggregate counts and trends broken down by tool name.",
            },
        ],
    },
    CategoryMeta {
        id: "analytics",
        title: "Analytics",
        tagline: "Every agent call, every token, every dollar — queryable from the CLI.",
        story: "If you can't answer \"what did my agents do today and what did it cost?\" you can't run them in production. This walkthrough starts at the 24-hour overview and drills down: which agents are busy, what each model is costing, and the raw request stream with latency and token counts. The same telemetry powers the dashboard, so nothing here is a toy view.",
        cost: "",
        feature_url: "https://systemprompt.io/features/analytics-and-observability",
        steps: &[
            StepMeta {
                script: "01-overview.sh",
                label: "Open the 24h and 7d overview",
                narrative: "Runs analytics overview for the last 24 hours and then --since 7d. One command gives you the same top-of-funnel numbers the admin dashboard shows — request volume, agent activity, cost, errors.",
                outcome: "You see a 24h and 7d snapshot of request count, active agents, total cost, and error rate in a single table.",
            },
            StepMeta {
                script: "02-agent-analytics.sh",
                label: "Drill into agent performance",
                narrative: "Aggregate stats, a ranked list of every agent with metrics, 7-day trends, and a deep-dive into developer_agent. This is how you find the one agent quietly burning budget or failing silently.",
                outcome: "You see a per-agent table with request count, success rate, and latency, a 7-day trend line, and a per-agent deep dive for developer_agent.",
            },
            StepMeta {
                script: "03-cost-analytics.sh",
                label: "Break cost down by model and agent",
                narrative: "Prints the cost summary, then breaks it down by model and by agent, then shows 7-day trends. This is your finance conversation: Haiku is 80% of calls and 12% of cost; Opus is the opposite.",
                outcome: "You see total spend, cost split by model, cost split by agent, and a 7-day cost trend — attributable to the row.",
            },
            StepMeta {
                script: "04-request-analytics.sh",
                label: "Inspect the raw request stream",
                narrative: "Shows request stats, the last 24 hours of individual AI calls, the model usage distribution, and 7-day volume trends. Every row is a real request you can click through to the full audit log.",
                outcome: "You see request-level rows with model, latency, and token counts, the model distribution, and a 7-day volume trend.",
            },
            StepMeta {
                script: "05-session-analytics.sh",
                label: "Zoom into sessions — stats, trends, and live",
                narrative: "Runs analytics sessions stats, a 7-day trend line, and the live active-session view. Sessions answer \"who's using it right now\" and \"is usage trending up\".",
                outcome: "Aggregate session counts, a 7-day trend, and a live list of sessions currently open against the platform.",
            },
            StepMeta {
                script: "06-content-traffic.sh",
                label: "Break down content and traffic",
                narrative: "analytics content stats, top pages, 7-day content trends, traffic sources, geo distribution, and device breakdown. Same binary that governs agents also tells you where your readers come from.",
                outcome: "Content engagement stats, top pages, traffic source and geo split, and a device breakdown for the public site.",
            },
            StepMeta {
                script: "07-conversations.sh",
                label: "Inspect agent conversations",
                narrative: "Prints conversation stats, 7-day trends, and the 20 most recent conversations. Every agent session is a conversation you can list and replay — no black-box chat log.",
                outcome: "Counts and a 7-day trend for conversations, plus a list of the 20 most recent with agent, status, and turn count.",
            },
            StepMeta {
                script: "08-tool-analytics.sh",
                label: "Close the loop on tool usage",
                narrative: "analytics tools stats, a ranked list of tools with per-tool metrics, and a 7-day trend. Tells you which MCP tools your agents are actually reaching for and whether usage is shifting.",
                outcome: "Per-tool call counts, latency, and error rate, plus a 7-day trend showing whether any tool is spiking or quietly dying.",
            },
        ],
    },
    CategoryMeta {
        id: "users",
        title: "Users & Access",
        tagline: "Identity, roles, sessions, and abuse response from one CLI.",
        story: "Before trusting a platform with production agents, you want to know how user identity actually works. This walkthrough lists the user directory, drills into a single user's role, confirms the current authenticated session and profile, then demonstrates the IP-ban lever end to end — add, verify, remove — so you know the abuse-response path is real and reversible.",
        cost: "",
        feature_url: "https://systemprompt.io/features/compliance",
        steps: &[
            StepMeta {
                script: "01-user-crud.sh",
                label: "List, count, stat, and search the user directory",
                narrative: "Runs admin users list, count, stats, and search admin to show the full directory, aggregate counts, and a keyword lookup. This is the baseline inventory every reviewer asks for.",
                outcome: "A paginated user list, a total count, a stats summary, and matching rows for the admin search term.",
            },
            StepMeta {
                script: "02-role-management.sh",
                label: "Drill into a single user and read their role assignment",
                narrative: "Grabs the first user ID from admin users list and pipes it into admin users show. You see the role, scope, and metadata the governance layer will key off of.",
                outcome: "A full user record with role, scope, and audit fields — the data governance rules match against.",
            },
            StepMeta {
                script: "03-session-management.sh",
                label: "Prove the current session and list available profiles",
                narrative: "Calls admin session show to display who the CLI is authenticated as, then admin session list to show every profile the operator can switch into. This is how you confirm blast radius before running anything mutating.",
                outcome: "Current session identity with auth source, plus the full list of named profiles available for switching.",
            },
            StepMeta {
                script: "04-ip-ban.sh",
                label: "Add, verify, and revoke an IP ban end to end",
                narrative: "Lists current bans, adds 192.168.99.99 with a reason, lists again to confirm, then removes it and lists a third time. A full mutation cycle in one script, leaving no residue behind.",
                outcome: "The test IP appears in the ban list after add, disappears after remove, and the before and after lists match — the abuse-response lever is real and reversible.",
            },
        ],
    },
];
