# SystemPrompt Profile: Production
# Default production profile for Docker deployments

name: prod
display_name: Production
site:
  name: SystemPrompt
  github_link: null
  service_display_name: SystemPrompt
  service_version: null
database:
  type: postgres
server:
  host: 0.0.0.0
  port: 8080
  api_server_url: null
  api_internal_url: null
  api_external_url: null
  use_https: true
  cors_allowed_origins: []
paths:
  system: /app
  core: /app
  services: /app/services
  skills: /app/services/skills
  config: /app/services/config/config.yaml
  storage: /app/storage
  cargo_target: null
  binary_dir: /app/bin
  geoip_database: null
  ai_config: /app/services/ai/config.yaml
  content_config: /app/services/content/config.yaml
  web_config: /app/services/web/config.yaml
  web_metadata: /app/services/web/metadata.yaml
  web_path: /app/web
  scg_templates: null
  scg_assets: null
  dockerfile: null
  web_dist: /app/web
security:
  jwt_issuer: systemprompt
  jwt_access_token_expiration: 86400
  jwt_refresh_token_expiration: 2592000
  jwt_audiences:
  - web
  - api
  - a2a
  - mcp
rate_limits:
  disabled: false
  oauth_public_per_second: 2
  oauth_auth_per_second: 2
  contexts_per_second: 50
  tasks_per_second: 10
  artifacts_per_second: 15
  agent_registry_per_second: 20
  agents_per_second: 3
  mcp_registry_per_second: 20
  mcp_per_second: 100
  stream_per_second: 1
  content_per_second: 20
  burst_multiplier: 2
runtime:
  environment: production
  log_level: normal
  output_format: json
  no_color: true
  non_interactive: true
extensions: null
cloud:
  credentials_path: null
  tenants_path: null
  tenant_id: null
  enabled: false
  validation: strict
secrets:
  secrets_path: null
  validation: strict
  source: env
