{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.secretName" . }}
  labels: {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  anthropic: {{ .Values.secrets.anthropicApiKey | quote }}
  openai: {{ .Values.secrets.openaiApiKey | quote }}
  gemini: {{ .Values.secrets.geminiApiKey | quote }}
{{- end }}
