//! What every conversation table needs to draw one row, and the two sources
//! that provide it: the conversations page's fact row and the skill page's
//! conversation row.

use chrono::{DateTime, Utc};
use systemprompt::identifiers::ContextId;

use super::view::ConversationRowView;
use crate::repositories::analysis::conversations::ConversationFactRow;
use crate::repositories::analysis::skills::SkillConversationRow;

// Why: what every conversation table needs to draw one row.
pub(crate) struct RowFacts<'a> {
    pub context_id: &'a ContextId,
    pub title: &'a str,
    pub judge_title: Option<&'a str>,
    pub user_id: &'a str,
    pub display_name: Option<&'a str>,
    pub client_session_id: Option<&'a str>,
    pub group_name: Option<&'a str>,
    pub project_name: Option<&'a str>,
    pub client_kind: &'a str,
    pub client_attestation: &'a str,
    pub model: Option<&'a str>,
    pub models: &'a [String],
    pub turn_count: i64,
    pub tool_calls_intended: i64,
    pub tool_calls_executed: i64,
    pub tool_calls_failed: i64,
    pub artifacts: i64,
    pub error_count: i64,
    pub request_count: i64,
    pub gov_deny: i64,
    pub safety_findings: i64,
    pub safety_blocked: i64,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub cache_tokens: i64,
    pub cost_microdollars: i64,
    pub p95_latency_ms: Option<i32>,
    pub duration_seconds: i64,
    // Why: summed turn latency; only the fact row carries it.
    pub active_ms: Option<i64>,
    pub is_continuation: bool,
    pub prev_context_id: Option<&'a str>,
    pub prev_title: Option<&'a str>,
    pub skills: &'a [String],
    pub skills_used: &'a [String],
    pub first_at: DateTime<Utc>,
    pub last_at: DateTime<Utc>,
    pub judge_status: Option<&'a str>,
    pub category: Option<&'a str>,
    pub outcome: Option<&'a str>,
    pub completion: Option<i16>,
    pub summary: Option<&'a str>,
    pub rationale: Option<&'a str>,
    pub turn_tokens: &'a [i64],
}

impl ConversationRowView {
    pub(crate) fn from_fact(r: &ConversationFactRow) -> Self {
        Self::new(&RowFacts {
            context_id: &r.context_id,
            title: &r.title,
            judge_title: r.judge_title.as_deref(),
            user_id: r.user_id.as_str(),
            display_name: r.display_name.as_deref(),
            client_session_id: r.client_session_id.as_deref(),
            group_name: r.group_name.as_deref(),
            project_name: r.project_name.as_deref(),
            client_kind: &r.client_kind,
            client_attestation: &r.client_attestation,
            model: r.model.as_deref(),
            models: &r.models,
            turn_count: r.turn_count,
            tool_calls_intended: r.tool_calls_intended,
            tool_calls_executed: r.tool_calls_executed,
            tool_calls_failed: r.tool_calls_failed,
            artifacts: r.artifact_count,
            error_count: r.error_count,
            request_count: r.request_count,
            gov_deny: r.gov_deny,
            safety_findings: r.safety_findings,
            safety_blocked: r.safety_blocked,
            input_tokens: r.input_tokens,
            output_tokens: r.output_tokens,
            cache_tokens: r.cache_read_tokens + r.cache_creation_tokens,
            cost_microdollars: r.cost_microdollars,
            p95_latency_ms: r.p95_latency_ms,
            duration_seconds: r.duration_seconds,
            active_ms: Some(r.active_ms),
            is_continuation: r.continuation.is_continuation,
            prev_context_id: r.continuation.prev_context_id.as_deref(),
            prev_title: r.continuation.prev_title.as_deref(),
            skills: &r.skills,
            skills_used: &r.skills_used,
            first_at: r.first_at,
            last_at: r.last_at,
            judge_status: r.judge_status.as_deref(),
            category: r.category.as_deref(),
            outcome: r.outcome.as_deref(),
            completion: r.completion,
            summary: r.summary.as_deref(),
            rationale: r.completion_rationale.as_deref(),
            turn_tokens: &r.turn_tokens,
        })
    }

    pub(crate) fn from_skill_row(r: &SkillConversationRow) -> Self {
        Self::new(&RowFacts {
            context_id: &r.context_id,
            title: &r.title,
            judge_title: r.judge_title.as_deref(),
            user_id: r.user_id.as_str(),
            display_name: r.display_name.as_deref(),
            client_session_id: r.client_session_id.as_deref(),
            group_name: r.group_name.as_deref(),
            project_name: r.project_name.as_deref(),
            client_kind: &r.client_kind,
            client_attestation: "unknown",
            model: r.model.as_deref(),
            models: &r.models,
            turn_count: r.turn_count,
            tool_calls_intended: r.tool_calls,
            tool_calls_executed: 0,
            tool_calls_failed: r.tool_calls_failed,
            artifacts: r.artifacts,
            error_count: r.error_count,
            request_count: r.turn_count,
            gov_deny: r.gov_deny,
            safety_findings: 0,
            safety_blocked: 0,
            input_tokens: r.total_tokens,
            output_tokens: 0,
            cache_tokens: r.cache_tokens,
            cost_microdollars: r.cost_microdollars,
            p95_latency_ms: r.p95_latency_ms,
            duration_seconds: r.duration_seconds,
            active_ms: None,
            is_continuation: false,
            prev_context_id: None,
            prev_title: None,
            skills: &r.skills,
            skills_used: &[],
            first_at: r.first_at,
            last_at: r.last_at,
            judge_status: None,
            category: r.category.as_deref(),
            outcome: r.outcome.as_deref(),
            completion: r.completion,
            summary: r.summary.as_deref(),
            rationale: None,
            turn_tokens: &[],
        })
    }
}
