//! Blog API routes and handlers.
//!
//! Note: Content is served as static HTML files generated by the SCG pipeline,
//! NOT via API endpoints. This module only provides:
//! - Link tracking API (for analytics/admin)
//! - Redirect router (for tracked link clicks)
//! - Search API (for content search)

pub mod handlers;
mod types;

use std::sync::Arc;

use axum::{
    routing::{get, post},
    Router,
};
use sqlx::PgPool;

use crate::config::BlogConfigValidated;

pub use types::*;

/// Build the blog admin API router (link tracking + search).
///
/// Content is served as static HTML via the SCG pipeline, not this API.
/// This router provides link tracking endpoints for analytics and search.
pub fn router(pool: Arc<PgPool>, config: Option<Arc<BlogConfigValidated>>) -> Router {
    let state = BlogState { pool, config };

    Router::new()
        // Link management
        .route("/links/generate", post(handlers::generate_link_handler))
        .route("/links/click", post(handlers::record_click_handler))
        .route("/links", get(handlers::list_links_handler))
        .route(
            "/links/{link_id}/performance",
            get(handlers::link_performance_handler),
        )
        .route("/links/{link_id}/clicks", get(handlers::link_clicks_handler))
        .route(
            "/links/campaigns/{campaign_id}/performance",
            get(handlers::campaign_performance_handler),
        )
        .route("/links/journey", get(handlers::content_journey_handler))
        // Content search
        .route("/search", get(handlers::search_handler))
        .with_state(state)
}

/// Redirect router (mounted separately at /r/).
pub fn redirect_router(pool: Arc<PgPool>) -> Router {
    Router::new()
        .route("/{short_code}", get(handlers::redirect_handler))
        .with_state(pool)
}

/// State shared across all blog API handlers.
#[derive(Clone)]
pub struct BlogState {
    pub pool: Arc<PgPool>,
    pub config: Option<Arc<BlogConfigValidated>>,
}
