INSERT INTO content_performance_metrics (
  id,
  content_id,
  total_views,
  unique_visitors,
  avg_time_on_page_seconds,
  shares_total,
  shares_linkedin,
  shares_twitter,
  comments_count,
  search_impressions,
  search_clicks,
  avg_search_position,
  views_last_7_days,
  views_last_30_days,
  trend_direction,
  updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, CAST($12 AS REAL), $13, $14, $15, CURRENT_TIMESTAMP)
ON CONFLICT(content_id) DO UPDATE SET
  total_views = EXCLUDED.total_views,
  unique_visitors = EXCLUDED.unique_visitors,
  avg_time_on_page_seconds = EXCLUDED.avg_time_on_page_seconds,
  shares_total = EXCLUDED.shares_total,
  shares_linkedin = EXCLUDED.shares_linkedin,
  shares_twitter = EXCLUDED.shares_twitter,
  comments_count = EXCLUDED.comments_count,
  search_impressions = EXCLUDED.search_impressions,
  search_clicks = EXCLUDED.search_clicks,
  avg_search_position = EXCLUDED.avg_search_position,
  views_last_7_days = EXCLUDED.views_last_7_days,
  views_last_30_days = EXCLUDED.views_last_30_days,
  trend_direction = EXCLUDED.trend_direction,
  updated_at = CURRENT_TIMESTAMP
