use serde::Serialize;

use super::apm;
use super::data;
use super::data_analyses;
use super::BuildTemplateDataParams;
use crate::admin::handlers::ssr::ssr_control_center::types::{
    SessionGroup, SkillEffectivenessEntry, StarRating,
};

pub(in crate::admin) struct AssembleInput<'a> {
    pub params: &'a BuildTemplateDataParams<'a>,
    pub counts: data::SessionCounts,
    pub gam: data::GamificationData,
    pub health: data::HealthData,
    pub analyses: data_analyses::AnalysesData,
    pub adoption: data_analyses::SkillAdoption,
    pub apm: apm::ApmData,
    pub report: super::super::types::ReportData,
}

#[derive(Serialize)]
#[allow(clippy::struct_excessive_bools)]
pub(in crate::admin) struct TemplateData<'a> {
    pub page: &'static str,
    pub title: &'static str,
    pub cc_initial_json: &'a str,
    pub username: &'a str,
    pub tier_name: &'a str,
    pub has_any_data: bool,
    pub status_filter: &'a str,
    pub active_count: usize,
    pub analysed_count: usize,
    pub unanalysed_count: usize,
    pub total_session_count: usize,
    pub has_gamification: bool,
    pub rank_level: i32,
    pub rank_name: &'a str,
    pub total_xp: i64,
    pub xp_to_next_rank: i64,
    pub next_rank_name: &'a str,
    pub current_streak: i32,
    pub longest_streak: i32,
    pub achievements_count: usize,
    pub achievements_total: usize,
    pub xp_progress_pct: i64,
    pub today: &'a super::super::types::TodayObj,
    pub session_groups: &'a [SessionGroup],
    pub has_session_groups: bool,
    pub top_tools: &'a [serde_json::Value],
    pub has_top_tools: bool,
    pub skill_effectiveness: Vec<SkillEffectivenessEntry>,
    pub has_skill_effectiveness: bool,
    pub skills_usage: &'a [&'a crate::admin::types::conversation_analytics::EntityUsageSummary],
    pub has_skills_usage: bool,
    pub agents_usage: &'a [&'a crate::admin::types::conversation_analytics::EntityUsageSummary],
    pub has_agents_usage: bool,
    pub mcp_usage: &'a [&'a crate::admin::types::conversation_analytics::EntityUsageSummary],
    pub has_mcp_usage: bool,
    pub skill_ratings: &'a [crate::admin::types::conversation_analytics::SkillRating],
    pub has_skill_ratings: bool,
    pub has_health: bool,
    pub health: &'a super::super::types::HealthObj,
    pub recent_analyses: &'a [super::super::types::AnalysisEntry],
    pub has_recent_analyses: bool,
    pub recommendations: &'a [super::super::types::AnalysisEntry],
    pub has_recommendations: bool,
    pub unused_skills: &'a [String],
    pub has_unused_skills: bool,
    pub skill_adoption_pct: usize,
    pub total_skills_available: usize,
    pub total_skills_used: usize,
    pub has_skill_adoption: bool,
    pub achievement_progress: &'a [super::super::types::AchievementProgress],
    pub has_achievement_progress: bool,
    pub today_summary: &'a super::super::types::TodaySummaryObj,
    pub has_today_summary: bool,
    pub hourly_breakdown: &'a [super::super::types::HourlyEntry],
    pub performance_summary: &'a super::super::types::PerfSummaryObj,
    pub report: &'a super::super::types::ReportData,
    pub has_report: bool,
}

pub(in crate::admin) fn assemble_template<'a>(input: &'a AssembleInput<'a>) -> TemplateData<'a> {
    let AssembleInput {
        params,
        counts,
        gam,
        health,
        analyses,
        adoption,
        apm,
        report,
    } = input;

    let skill_effectiveness: Vec<SkillEffectivenessEntry> = params
        .skill_effectiveness
        .iter()
        .map(|s| SkillEffectivenessEntry {
            skill_name: s.skill_name.clone(),
            total_uses: s.total_uses,
            sessions_used_in: s.sessions_used_in,
            avg_effectiveness: format!("{:.1}", s.avg_effectiveness),
            scored_sessions: s.scored_sessions,
            goal_achievement_pct: format!("{:.0}", s.goal_achievement_pct),
            has_score: s.scored_sessions > 0,
            stars: StarRating {
                star_1: s.avg_effectiveness.round() >= 1.0,
                star_2: s.avg_effectiveness.round() >= 2.0,
                star_3: s.avg_effectiveness.round() >= 3.0,
                star_4: s.avg_effectiveness.round() >= 4.0,
                star_5: s.avg_effectiveness.round() >= 5.0,
            },
        })
        .collect();

    TemplateData {
        page: "control-center",
        title: "Control Center",
        cc_initial_json: &apm.cc_initial_json,
        username: &params.user_ctx.username,
        tier_name: &params.mkt_ctx.tier_name,
        has_any_data: counts.has_any_data,
        status_filter: params.status_filter,
        active_count: counts.active,
        analysed_count: counts.analysed_closed,
        unanalysed_count: params.session_groups.len() - counts.analysed_closed,
        total_session_count: params.session_groups.len(),
        has_gamification: gam.has_gamification,
        rank_level: gam.rank_level,
        rank_name: &gam.rank_name,
        total_xp: gam.total_xp,
        xp_to_next_rank: gam.xp_to_next,
        next_rank_name: &gam.next_rank_name,
        current_streak: gam.current_streak,
        longest_streak: gam.longest_streak,
        achievements_count: gam.achievements_count,
        achievements_total: gam.achievements_total,
        xp_progress_pct: gam.xp_progress_pct,
        today: &apm.today_obj,
        session_groups: params.session_groups,
        has_session_groups: !params.session_groups.is_empty(),
        top_tools: params.tools_with_pct,
        has_top_tools: !params.tools_with_pct.is_empty(),
        has_skill_effectiveness: !params.skill_effectiveness.is_empty(),
        skill_effectiveness,
        skills_usage: params.skills_usage,
        has_skills_usage: !params.skills_usage.is_empty(),
        agents_usage: params.agents_usage,
        has_agents_usage: !params.agents_usage.is_empty(),
        mcp_usage: params.mcp_usage,
        has_mcp_usage: !params.mcp_usage.is_empty(),
        skill_ratings: params.skill_ratings,
        has_skill_ratings: !params.skill_ratings.is_empty(),
        has_health: health.has_health,
        health: &health.health_obj,
        recent_analyses: &analyses.recent_analyses_json,
        has_recent_analyses: !params.recent_analyses.is_empty(),
        recommendations: &analyses.recommendations_json,
        has_recommendations: !analyses.recommendations_json.is_empty(),
        unused_skills: params.unused_skills,
        has_unused_skills: !params.unused_skills.is_empty(),
        skill_adoption_pct: adoption.adoption_pct,
        total_skills_available: adoption.total_available,
        total_skills_used: adoption.total_used,
        has_skill_adoption: adoption.total_available > 0,
        achievement_progress: &gam.achievement_progress,
        has_achievement_progress: !gam.achievement_progress.is_empty(),
        today_summary: &apm.today_summary_obj,
        has_today_summary: params.today_summary.sessions_count > 0,
        hourly_breakdown: &apm.hourly_json,
        performance_summary: &apm.perf_json,
        report,
        has_report: !params.daily_summaries.is_empty(),
    }
}
