//! The recorded status table, and the diff against the checked-in baseline.
//!
//! The invariants in [`crate::status_contract`] catch the failures that are
//! always wrong. This catches the ones that are merely *changed*: a route that
//! used to answer 404 and now answers 500, or an authorisation boundary that
//! quietly moved. Neither is necessarily a bug, so the baseline is reviewed
//! rather than enforced blind — but it can never change without someone
//! saying so in the diff.

use std::fmt::Write as _;
use std::path::PathBuf;

use axum::http::StatusCode;

use crate::principal::Principal;
use crate::route_source::MountedRoute;

const BASELINE_FILE: &str = "baseline.txt";
const UPDATE_ENV: &str = "UPDATE_CONTRACT_BASELINE";

pub fn baseline_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(BASELINE_FILE)
}

// One line per route: the method and path, then the status each principal
// receives. Sorted, so the file diffs cleanly.
pub fn render(observed: &[(MountedRoute, Vec<(Principal, StatusCode)>)]) -> String {
    let mut out = String::from(
        "# Admin HTTP contract baseline — generated by `just test-contract`.\n\
         # One line per mounted route: the status each principal receives.\n\
         # Regenerate with UPDATE_CONTRACT_BASELINE=1 and review every change.\n",
    );
    let mut lines: Vec<String> = observed
        .iter()
        .map(|(route, statuses)| {
            let mut line = format!("{:<7}{}", route.method.to_uppercase(), route.template);
            let _ = write!(line, "{}", " ".repeat(pad(&line)));
            for (principal, status) in statuses {
                let _ = write!(line, " {}={}", principal.label(), status.as_u16());
            }
            line
        })
        .collect();
    lines.sort();
    for line in lines {
        out.push_str(&line);
        out.push('\n');
    }
    out
}

fn pad(line: &str) -> usize {
    const COLUMN: usize = 60;
    COLUMN.saturating_sub(line.chars().count())
}

// Compare against the checked-in file, or rewrite it when explicitly asked.
// Panics when the observed table differs and no update was requested.
pub fn assert_matches(rendered: &str) {
    let path = baseline_path();

    if std::env::var(UPDATE_ENV).is_ok_and(|v| v == "1") {
        std::fs::write(&path, rendered).expect("write contract baseline");
        eprintln!("contract baseline rewritten: {}", path.display());
        return;
    }

    let Ok(existing) = std::fs::read_to_string(&path) else {
        std::fs::write(&path, rendered).expect("write initial contract baseline");
        eprintln!("contract baseline created: {}", path.display());
        return;
    };

    if existing == rendered {
        return;
    }

    let diff = line_diff(&existing, rendered);
    panic!(
        "the admin HTTP contract changed:\n{diff}\n\
         Every line above is a status the API now returns differently. If the change is \
         deliberate, list it in the PR and re-record with:\n    \
         {UPDATE_ENV}=1 cargo test --manifest-path tests/Cargo.toml -p admin-contract-tests\n"
    );
}

fn line_diff(before: &str, after: &str) -> String {
    let old: Vec<&str> = before.lines().filter(|l| !l.starts_with('#')).collect();
    let new: Vec<&str> = after.lines().filter(|l| !l.starts_with('#')).collect();

    let mut out = String::new();
    for line in &old {
        if !new.contains(line) {
            let _ = writeln!(out, "  - {line}");
        }
    }
    for line in &new {
        if !old.contains(line) {
            let _ = writeln!(out, "  + {line}");
        }
    }
    out
}
