//! Static asset manifest for the admin dashboard.
//!
//! The admin crate owns the front-end it serves: per-page scripts under
//! `storage/files/js/pages/` and the generated `admin-bundle.css`. The facade
//! merges this with the public-site manifest in `required_assets`.

use std::path::Path;

use systemprompt::extension::{AssetDefinition, AssetPaths, AssetType};

macro_rules! page_js {
    ($p:expr, $name:literal) => {
        AssetDefinition::js($p.join($name), concat!("js/pages/", $name))
    };
}

#[must_use]
pub fn admin_assets(paths: &dyn AssetPaths) -> Vec<AssetDefinition> {
    let storage_css = paths.storage_files().join("css");
    let storage_js = paths.storage_files().join("js");

    let mut assets = page_js_assets(&storage_js);
    assets.push(admin_bundle_css(&storage_css));
    assets
}

fn page_js_assets(storage_js: &Path) -> Vec<AssetDefinition> {
    let pages = storage_js.join("pages");
    vec![
        page_js!(&pages, "admin-bridge-setup.js"),
        page_js!(&pages, "admin-catalog-filter.js"),
        page_js!(&pages, "admin-contexts.js"),
        page_js!(&pages, "admin-entities.js"),
        page_js!(&pages, "admin-invite.js"),
        page_js!(&pages, "admin-invites-panel.js"),
        page_js!(&pages, "admin-login.js"),
        page_js!(&pages, "admin-report-print.js"),
        page_js!(&pages, "admin-settings.js"),
        page_js!(&pages, "admin-setup-verified.js"),
        page_js!(&pages, "admin-user-detail.js"),
        page_js!(&pages, "admin-user-sessions.js"),
        page_js!(&pages, "admin-users-actions.js"),
        page_js!(&pages, "admin-users.js"),
        page_js!(&pages, "management-department-detail.js"),
        page_js!(&pages, "management-departments.js"),
        page_js!(&pages, "profile-connect-code.js"),
        page_js!(&pages, "profile-salesforce.js"),
    ]
}

// Why: the bundle is generated by `bundle_admin_css`, so it is optional at
// registration time; a fresh checkout has not produced it yet.
fn admin_bundle_css(storage_css: &Path) -> AssetDefinition {
    AssetDefinition::builder(
        storage_css.join("admin-bundle.css"),
        "css/admin-bundle.css",
        AssetType::Css,
    )
    .optional()
    .build()
}
