#!/bin/bash
# SystemPrompt Template - First-Time Setup Script
# Run this after cloning the repository

set -e

echo "=========================================="
echo "  SystemPrompt Template Setup"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
DB_API_URL="${SYSTEMPROMPT_DB_API_URL:-http://localhost:8085}"

# Check prerequisites
echo "Checking prerequisites..."

check_command() {
    if command -v "$1" &> /dev/null; then
        echo -e "${GREEN}✓${NC} $1 found"
        return 0
    else
        echo -e "${RED}✗${NC} $1 not found"
        return 1
    fi
}

MISSING=0
check_command "cargo" || MISSING=1
check_command "docker" || MISSING=1
check_command "just" || { echo -e "${YELLOW}!${NC} 'just' not found - install with: cargo install just"; MISSING=1; }
check_command "curl" || MISSING=1
check_command "jq" || { echo -e "${YELLOW}!${NC} 'jq' not found - install with: sudo apt install jq"; MISSING=1; }

if [ $MISSING -eq 1 ]; then
    echo ""
    echo -e "${RED}Please install missing prerequisites and try again.${NC}"
    exit 1
fi

echo ""

# Install git hooks
echo "Installing git hooks..."
if [ -d ".git" ]; then
    ln -sf ../../infrastructure/scripts/pre-commit-core.sh .git/hooks/pre-commit
    chmod +x .git/hooks/pre-commit
    echo -e "${GREEN}✓${NC} Pre-commit hook installed (protects core/ from edits)"
else
    echo -e "${YELLOW}!${NC} Not a git repository - skipping hooks"
fi

echo ""

# Check systemprompt-db is running
echo "Checking systemprompt-db API..."
if ! curl -sf "$DB_API_URL/health" >/dev/null 2>&1; then
    echo -e "${RED}✗${NC} systemprompt-db API not running at $DB_API_URL"
    echo ""
    echo "Please start systemprompt-db first:"
    echo "  cd ../systemprompt-db && docker-compose -f docker-compose.local.yml up -d"
    echo ""
    echo "Or set SYSTEMPROMPT_DB_API_URL if using a different host."
    exit 1
fi
echo -e "${GREEN}✓${NC} systemprompt-db API available"

echo ""

# Prompt for tenant name
DEFAULT_TENANT=$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr '-' '_')
echo "Database provisioning"
echo "---------------------"
echo "A tenant name is used to create an isolated database for this project."
echo ""
read -p "Tenant name [$DEFAULT_TENANT]: " TENANT_NAME
TENANT_NAME="${TENANT_NAME:-$DEFAULT_TENANT}"

# Validate: lowercase, alphanumeric, underscores only, 3-32 chars
if ! [[ "$TENANT_NAME" =~ ^[a-z][a-z0-9_]{2,31}$ ]]; then
    echo -e "${RED}✗${NC} Invalid tenant name."
    echo "  - Must start with a lowercase letter"
    echo "  - Only lowercase letters, numbers, and underscores"
    echo "  - 3-32 characters"
    exit 1
fi

echo ""

# Provision database via API
echo "Provisioning database '$TENANT_NAME'..."

RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$DB_API_URL/api/v1/tenants" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"$TENANT_NAME\",\"metadata\":{\"environment\":\"development\",\"source\":\"systemprompt-template\"}}")

HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
BODY=$(echo "$RESPONSE" | sed '$d')

case "$HTTP_CODE" in
    201)
        # Get connection string and replace Docker hostname with localhost
        CONNECTION_STRING=$(echo "$BODY" | jq -r '.data.connection_string' | sed 's/@postgres:/@localhost:/')
        echo -e "${GREEN}✓${NC} Database provisioned successfully"
        ;;
    409)
        echo -e "${YELLOW}!${NC} Tenant '$TENANT_NAME' already exists"
        echo ""
        echo "Enter the DATABASE_URL for your existing tenant."
        echo "Format: postgresql://USER:PASSWORD@localhost:6432/DATABASE"
        echo ""
        read -p "DATABASE_URL: " CONNECTION_STRING
        if [ -z "$CONNECTION_STRING" ]; then
            echo -e "${RED}✗${NC} DATABASE_URL is required"
            exit 1
        fi
        ;;
    *)
        echo -e "${RED}✗${NC} Failed to provision database (HTTP $HTTP_CODE)"
        echo "$BODY" | jq . 2>/dev/null || echo "$BODY"
        exit 1
        ;;
esac

echo ""

# Setup .env.secrets
echo "Setting up .env.secrets..."
if [ ! -f ".env.secrets" ]; then
    cp .env.secrets.example .env.secrets
    echo -e "${GREEN}✓${NC} Created .env.secrets from template"
fi

# Update DATABASE_URL in .env.secrets (using grep+cat to handle special chars in password)
grep -v "^DATABASE_URL=" .env.secrets > .env.secrets.tmp || true
echo "DATABASE_URL=$CONNECTION_STRING" >> .env.secrets.tmp
mv .env.secrets.tmp .env.secrets
echo -e "${GREEN}✓${NC} DATABASE_URL saved to .env.secrets"

echo ""

# Create .env.local for local development
echo "Setting up .env.local..."
if [ ! -f ".env.local" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

    cat > .env.local << EOF
# SystemPrompt Template - Local Development Environment
# Generated by setup-dev.sh

# Paths
SYSTEM_PATH=${PROJECT_ROOT}
WEB_DIR=${PROJECT_ROOT}/core/web/dist
SYSTEMPROMPT_CONFIG_PATH=${PROJECT_ROOT}/crates/services/config/config.yml
SYSTEMPROMPT_SERVICES_PATH=${PROJECT_ROOT}/crates/services
AI_CONFIG_PATH=${PROJECT_ROOT}/config/ai.yaml
CONTENT_CONFIG_PATH=${PROJECT_ROOT}/crates/services/content/config.yml

# Server
HOST=127.0.0.1
PORT=8080
API_SERVER_URL=http://localhost:8080

# Site
SITENAME=$TENANT_NAME
GITHUB_LINK=https://github.com/your-org/your-repo

# Logging
RUST_LOG=info

# JWT
JWT_ISSUER=systemprompt-$TENANT_NAME
JWT_ACCESS_TOKEN_EXPIRATION=86400
JWT_REFRESH_TOKEN_EXPIRATION=2592000

# CORS
CORS_ALLOWED_ORIGINS=http://localhost:8080,http://localhost:5173
EOF
    echo -e "${GREEN}✓${NC} Created .env.local"
else
    echo -e "${GREEN}✓${NC} .env.local already exists"
fi

echo ""

# Build
echo "Building project (this may take a few minutes on first run)..."
./infrastructure/scripts/build.sh debug
echo -e "${GREEN}✓${NC} Build complete"

echo ""

# Run migrations
echo "Running database migrations..."
set -a
source .env.local
if [ -f .env.secrets ]; then source .env.secrets; fi
set +a
./core/target/debug/systemprompt db migrate || {
    echo -e "${RED}✗${NC} Migration failed - check your DATABASE_URL"
    exit 1
}
echo -e "${GREEN}✓${NC} Migrations complete"

echo ""
echo "=========================================="
echo -e "${GREEN}  Setup Complete!${NC}"
echo "=========================================="
echo ""
echo "Your database: $TENANT_NAME"
echo ""
echo "Next steps:"
echo "  1. Run: just start"
echo "  2. Open: http://localhost:8080"
echo ""
