#!/bin/bash
# SystemPrompt Template - First-Time Setup Script
# Run this after cloning the repository

set -e

echo "=========================================="
echo "  SystemPrompt Template Setup"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "Checking prerequisites..."

check_command() {
    if command -v "$1" &> /dev/null; then
        echo -e "${GREEN}✓${NC} $1 found"
        return 0
    else
        echo -e "${RED}✗${NC} $1 not found"
        return 1
    fi
}

MISSING=0
check_command "cargo" || MISSING=1
check_command "docker" || MISSING=1
check_command "just" || { echo -e "${YELLOW}!${NC} 'just' not found - install with: cargo install just"; MISSING=1; }

if [ $MISSING -eq 1 ]; then
    echo ""
    echo -e "${RED}Please install missing prerequisites and try again.${NC}"
    exit 1
fi

echo ""

# Install git hooks
echo "Installing git hooks..."
if [ -d ".git" ]; then
    ln -sf ../../infrastructure/scripts/pre-commit-core.sh .git/hooks/pre-commit
    chmod +x .git/hooks/pre-commit
    echo -e "${GREEN}✓${NC} Pre-commit hook installed (protects core/ from edits)"
else
    echo -e "${YELLOW}!${NC} Not a git repository - skipping hooks"
fi

echo ""

# Setup environment
echo "Setting up environment..."
if [ ! -f ".env.secrets" ]; then
    cp .env.secrets.example .env.secrets
    echo -e "${GREEN}✓${NC} Created .env.secrets from template"
    echo -e "${YELLOW}!${NC} Please edit .env.secrets with your configuration"
else
    echo -e "${GREEN}✓${NC} .env.secrets already exists"
fi

# Create .env.local for local development
if [ ! -f ".env.local" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

    cat > .env.local << EOF
# SystemPrompt Template - Local Development Environment
# Generated by setup-dev.sh

# Paths
SYSTEM_PATH=${PROJECT_ROOT}
WEB_DIR=${PROJECT_ROOT}/core/web/dist
SYSTEMPROMPT_CONFIG_PATH=${PROJECT_ROOT}/crates/services/config/config.yml
SYSTEMPROMPT_SERVICES_PATH=${PROJECT_ROOT}/crates/services
AI_CONFIG_PATH=${PROJECT_ROOT}/config/ai.yaml
CONTENT_CONFIG_PATH=${PROJECT_ROOT}/crates/services/content/config.yml

# Server
HOST=127.0.0.1
PORT=8080
API_SERVER_URL=http://localhost:8080

# Site
SITENAME=template
GITHUB_LINK=https://github.com/your-org/your-repo

# Logging
RUST_LOG=info

# JWT
JWT_ISSUER=systemprompt-template
JWT_ACCESS_TOKEN_EXPIRATION=86400
JWT_REFRESH_TOKEN_EXPIRATION=2592000

# CORS
CORS_ALLOWED_ORIGINS=http://localhost:8080,http://localhost:5173
EOF
    echo -e "${GREEN}✓${NC} Created .env.local"
else
    echo -e "${GREEN}✓${NC} .env.local already exists"
fi

echo ""

# Start PostgreSQL
echo "Starting PostgreSQL..."
if docker ps --format '{{.Names}}' | grep -q 'systemprompt-postgres'; then
    echo -e "${GREEN}✓${NC} PostgreSQL already running"
else
    docker-compose up -d postgres
    echo "Waiting for PostgreSQL to be ready..."
    sleep 5
    echo -e "${GREEN}✓${NC} PostgreSQL started"
fi

echo ""

# Build
echo "Building project (this may take a few minutes on first run)..."
./infrastructure/scripts/build.sh debug
echo -e "${GREEN}✓${NC} Build complete"

echo ""

# Run migrations
echo "Running database migrations..."
set -a
source .env.local
if [ -f .env.secrets ]; then source .env.secrets; fi
set +a
./core/target/debug/systemprompt db migrate || true
echo -e "${GREEN}✓${NC} Migrations complete"

echo ""
echo "=========================================="
echo -e "${GREEN}  Setup Complete!${NC}"
echo "=========================================="
echo ""
echo "Next steps:"
echo "  1. Edit .env.secrets with your database and API keys"
echo "  2. Run: just start"
echo "  3. Open: http://localhost:8080"
echo ""
