use chrono::NaiveDate;

#[derive(Debug, Default, sqlx::FromRow)]
pub struct DailySummaryRow {
    pub summary_date: NaiveDate,
    pub session_count: i32,
    pub avg_quality_score: Option<f32>,
    pub goals_achieved: i32,
    pub goals_partial: i32,
    pub goals_failed: i32,
    pub total_prompts: i64,
    pub total_tool_uses: i64,
    pub total_errors: i64,
    pub summary: String,
    pub patterns: Option<String>,
    pub skill_gaps: Option<String>,
    pub top_recommendation: Option<String>,
    pub daily_xp: i32,
    pub tags: String,
    pub avg_apm: Option<f32>,
    pub peak_apm: Option<f32>,
    pub avg_eapm: Option<f32>,
    pub peak_concurrency: i32,
    pub avg_concurrency: Option<f32>,
    pub total_input_bytes: i64,
    pub total_output_bytes: i64,
    pub peak_throughput_bps: i64,
    pub tool_diversity: i32,
    pub multitasking_score: Option<f32>,
    pub session_velocity: Option<f32>,
    pub achievements_unlocked: String,
    pub highlights: Option<String>,
    pub trends: Option<String>,
    pub category_distribution: Option<serde_json::Value>,
    pub plugins_count: i32,
    pub skills_count: i32,
    pub agents_count: i32,
    pub mcp_servers_count: i32,
    pub hooks_count: i32,
    pub health_score: Option<f32>,
    pub skill_effectiveness: Option<serde_json::Value>,
    pub avg_session_duration_minutes: Option<f32>,
    pub avg_turns_per_session: Option<f32>,
    pub total_corrections: i32,
    pub avg_automation_ratio: Option<f32>,
    pub plan_mode_sessions: i32,
}

#[derive(Debug)]
pub struct DailySummaryInput {
    pub session_count: i32,
    pub avg_quality_score: Option<f32>,
    pub goals_achieved: i32,
    pub goals_partial: i32,
    pub goals_failed: i32,
    pub total_prompts: i64,
    pub total_tool_uses: i64,
    pub total_errors: i64,
    pub summary: String,
    pub patterns: Option<String>,
    pub skill_gaps: Option<String>,
    pub top_recommendation: Option<String>,
    pub daily_xp: i32,
    pub tags: String,
    pub avg_apm: Option<f32>,
    pub peak_apm: Option<f32>,
    pub avg_eapm: Option<f32>,
    pub peak_concurrency: i32,
    pub avg_concurrency: Option<f32>,
    pub total_input_bytes: i64,
    pub total_output_bytes: i64,
    pub peak_throughput_bps: i64,
    pub tool_diversity: i32,
    pub multitasking_score: Option<f32>,
    pub session_velocity: Option<f32>,
    pub achievements_unlocked: String,
    pub highlights: Option<String>,
    pub trends: Option<String>,
    pub category_distribution: Option<serde_json::Value>,
    pub plugins_count: i32,
    pub skills_count: i32,
    pub agents_count: i32,
    pub mcp_servers_count: i32,
    pub hooks_count: i32,
    pub health_score: Option<f32>,
    pub skill_effectiveness: Option<serde_json::Value>,
    pub avg_session_duration_minutes: Option<f32>,
    pub avg_turns_per_session: Option<f32>,
    pub total_corrections: i32,
    pub avg_automation_ratio: Option<f32>,
    pub plan_mode_sessions: i32,
}

#[derive(Debug, Default, sqlx::FromRow, Clone, Copy)]
pub struct GlobalAverages {
    pub avg_sessions: Option<f32>,
    pub avg_quality: Option<f32>,
    pub avg_apm: Option<f32>,
    pub avg_peak_apm: Option<f32>,
    pub avg_error_rate: Option<f64>,
    pub avg_tool_diversity: Option<f32>,
    pub avg_multitasking: Option<f32>,
    pub avg_goal_rate: Option<f64>,
    pub avg_throughput: Option<i64>,
    pub total_users: Option<i64>,
}

pub(super) struct UpsertCloned {
    pub patterns: Option<String>,
    pub skill_gaps: Option<String>,
    pub top_recommendation: Option<String>,
    pub highlights: Option<String>,
    pub trends: Option<String>,
    pub category_distribution: Option<serde_json::Value>,
    pub skill_effectiveness: Option<serde_json::Value>,
}
