//! `robots.txt` and `llms.txt` are consumed by crawlers that will not tell us
//! when we get the format wrong, so the generated bytes are pinned here:
//! the crawl directives and their order, the private prefixes that must stay
//! disallowed, the absolute sitemap URL, and — for llms.txt — that a section
//! with no entries emits nothing at all rather than a dangling heading.

use systemprompt_web_extension::jobs::internals::{
    build_robots_txt_content, sort_entries_in_place, write_header, write_section,
};

#[test]
fn robots_allows_everything_except_the_private_prefixes() {
    let content = build_robots_txt_content("https://a.test").unwrap();
    assert!(content.starts_with("User-agent: *\nAllow: /\n"));
    for prefix in ["/api/", "/console/", "/_/"] {
        assert!(
            content.contains(&format!("Disallow: {prefix}\n")),
            "missing Disallow for {prefix}"
        );
    }
}

#[test]
fn robots_points_at_an_absolute_sitemap_url() {
    let content = build_robots_txt_content("https://a.test").unwrap();
    assert!(content.ends_with("Sitemap: https://a.test/sitemap.xml\n"));
}

#[test]
fn robots_does_not_normalise_a_trailing_slash_in_the_base_url() {
    let content = build_robots_txt_content("https://a.test/").unwrap();
    assert!(content.contains("Sitemap: https://a.test//sitemap.xml"));
}

#[test]
fn robots_disallow_lines_come_after_the_allow_block() {
    let content = build_robots_txt_content("https://a.test").unwrap();
    let allow = content.find("Allow: /").unwrap();
    let disallow = content.find("Disallow: /api/").unwrap();
    assert!(allow < disallow);
}

#[test]
fn the_llms_header_carries_both_quick_links() {
    let mut content = String::new();
    write_header(&mut content, "https://a.test").unwrap();
    assert!(content.starts_with("# Your Project Name\n"));
    assert!(content.contains("- Homepage: https://a.test\n"));
    assert!(content.contains("- Documentation: https://a.test/documentation\n"));
    assert!(content.ends_with("\n\n"));
}

#[test]
fn an_empty_section_emits_nothing() {
    let mut content = String::new();
    write_section::<String>(&mut content, "Services", &[]).unwrap();
    assert!(content.is_empty());
}

#[test]
fn a_section_writes_a_markdown_link_list_under_its_heading() {
    let mut content = String::new();
    write_section(
        &mut content,
        "Services",
        &[("Auth", "https://a.test/auth", "Identity")],
    )
    .unwrap();
    assert_eq!(
        content,
        "### Services\n\n- [Auth](https://a.test/auth): Identity\n\n"
    );
}

#[test]
fn sections_append_without_swallowing_the_previous_one() {
    let mut content = String::new();
    write_section(&mut content, "A", &[("t1", "u1", "d1")]).unwrap();
    write_section(&mut content, "B", &[("t2", "u2", "d2")]).unwrap();
    assert!(content.contains("### A\n"));
    assert!(content.contains("### B\n"));
    assert!(content.find("### A").unwrap() < content.find("### B").unwrap());
}

#[test]
fn entries_sort_by_title_only() {
    let mut items = vec![
        ("Zebra".to_owned(), "u1".to_owned(), "d1".to_owned()),
        ("apple".to_owned(), "u2".to_owned(), "d2".to_owned()),
        ("Apple".to_owned(), "u3".to_owned(), "d3".to_owned()),
    ];
    sort_entries_in_place(&mut items);
    let titles: Vec<&str> = items.iter().map(|i| i.0.as_str()).collect();
    assert_eq!(titles, vec!["Apple", "Zebra", "apple"]);
}
