use crate::models::Content;
use crate::repository::ContentRepository;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use std::sync::Arc;
use systemprompt_core_database::DatabaseProvider;

#[derive(Debug, Serialize, Deserialize, Copy, Clone)]
pub struct ExportStats {
    pub files_written: usize,
    pub bytes_written: u64,
    pub duration_secs: u64,
}

#[derive(Debug)]
pub struct ExportService {
    content_repo: ContentRepository,
}

impl ExportService {
    pub fn new(db: Arc<dyn DatabaseProvider>) -> Self {
        Self {
            content_repo: ContentRepository::new(db),
        }
    }

    pub async fn export_all(&self, sources: &[ContentSourceExport]) -> Result<ExportStats> {
        let start = std::time::Instant::now();
        let mut stats = ExportStats {
            files_written: 0,
            bytes_written: 0,
            duration_secs: 0,
        };

        for source in sources {
            let source_stats = self.export_source(source).await?;
            stats.files_written += source_stats.files_written;
            stats.bytes_written += source_stats.bytes_written;
        }

        stats.duration_secs = start.elapsed().as_secs();
        Ok(stats)
    }

    pub async fn export_source(&self, source: &ContentSourceExport) -> Result<ExportStats> {
        let mut stats = ExportStats {
            files_written: 0,
            bytes_written: 0,
            duration_secs: 0,
        };

        let content_items = self.content_repo.list_by_source(&source.source_id).await?;

        for item in content_items {
            let file_path = Path::new(&source.path)
                .join(&item.slug)
                .with_extension("md");
            Self::export_item(&item, &file_path)?;
            let file_size = fs::metadata(&file_path)?.len();
            stats.files_written += 1;
            stats.bytes_written += file_size;
        }

        Ok(stats)
    }

    fn export_item(content: &Content, file_path: &Path) -> Result<()> {
        if let Some(parent) = file_path.parent() {
            fs::create_dir_all(parent)?;
        }

        let frontmatter = Self::generate_frontmatter(content);
        let markdown = format!(
            "<!-- AUTOGENERATED FROM DATABASE - DO NOT EDIT DIRECTLY -->\n\
             <!-- Database is source of truth. Edit via API/CMS. -->\n\
             <!-- Last sync: {} -->\n\
             ---\n{}\n---\n\n{}",
            chrono::Utc::now().to_rfc3339(),
            frontmatter,
            content.body
        );

        fs::write(file_path, markdown)?;
        Ok(())
    }

    fn generate_frontmatter(content: &Content) -> String {
        let mut frontmatter = String::new();
        frontmatter.push_str(&format!("title: \"{}\"\n", escape_yaml(&content.title)));
        frontmatter.push_str(&format!("slug: \"{}\"\n", content.slug));
        frontmatter.push_str(&format!(
            "description: \"{}\"\n",
            escape_yaml(&content.description)
        ));
        frontmatter.push_str(&format!("author: \"{}\"\n", content.author));
        frontmatter.push_str(&format!("published_at: \"{}\"\n", content.published_at));
        frontmatter.push_str(&format!("category: \"{}\"\n", content.category_id));

        if let Some(image) = &content.image {
            frontmatter.push_str(&format!("image: \"{image}\"\n"));
        }

        if !content.keywords.is_empty() {
            frontmatter.push_str(&format!(
                "keywords: \"{}\"\n",
                escape_yaml(&content.keywords)
            ));
        }

        frontmatter.push_str(&format!("kind: \"{}\"\n", content.kind));
        frontmatter.push_str(&format!("public: {}\n", content.public));
        frontmatter.push_str(&format!("version_hash: \"{}\"\n", content.version_hash));

        if !content.links.is_empty() {
            frontmatter.push_str("links:\n");
            for link in &content.links {
                frontmatter.push_str(&format!("  - title: \"{}\"\n", escape_yaml(&link.title)));
                frontmatter.push_str(&format!("    url: \"{}\"\n", escape_yaml(&link.url)));
            }
        }

        frontmatter
    }
}

fn escape_yaml(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

#[derive(Debug, Clone)]
pub struct ContentSourceExport {
    pub source_id: String,
    pub path: String,
}
