[package]
name = "mcp-unit-tests"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
systemprompt-mcp-shared = { workspace = true }
systemprompt-mcp-agent = { workspace = true }
systemprompt-mcp-knowledge-bank = { workspace = true }
tokio = { workspace = true }
systemprompt = { workspace = true, features = ["full"] }
axum = { workspace = true }
serde_json = { workspace = true }
